config/routes.rb
OauthProvider::Application.routes.draw do

  resources :oauth_clients

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth',               :to => 'oauth#index',         :as => :oauth

  match '/oauth/account_info',  :to => 'oauth#account_info',  :as => :account_info

  devise_for :users

  root :to => "home#index"
end

app/controllers/oauth_controller.rb
require 'oauth/controllers/provider_controller'

class OauthController < ApplicationController
  include OAuth::Controllers::ProviderController

  alias :logged_in? :user_signed_in?
  alias :login_required :authenticate_user!

  def account_info
    oauth_params = OAuth::Helper.parse_header(env["HTTP_AUTHORIZATION"])
    user = OauthToken.find_by_token(oauth_params["oauth_token"]).user

    respond_to do |format|
      format.html { render :text => Decorators::AccountInfo.wrap(user) }
    end
  end

  protected

  def oauth1_authorize
    unless @token
      render :action=>"authorize_failure"
      return
    end

    unless @token.invalidated?
      if user_authorizes_token?
        @token.authorize!(current_user)
        callback_url  = @token.oob? ? @token.client_application.callback_url : @token.callback_url
        @redirect_url = URI.parse(callback_url) unless callback_url.blank?

        unless @redirect_url.to_s.blank?
          @redirect_url.query = @redirect_url.query.blank? ?
              "oauth_token=#{@token.token}&oauth_verifier=#{@token.verifier}" :
              @redirect_url.query + "&oauth_token=#{@token.token}&oauth_verifier=#{@token.verifier}"

          # sign out current user
          sign_out

          redirect_to @redirect_url.to_s
        else
          render :action => "authorize_success"
        end
      else
        @token.invalidate!
        render :action => "authorize_failure"
      end
    else
      render :action => "authorize_failure"
    end
  end

  # Override this to match your authorization page form
  # It currently expects a checkbox called authorize
  def user_authorizes_token?
     true
  end

  # should authenticate and return a user if valid password.
  # This example should work with most Authlogic or Devise. Uncomment it
  # def authenticate_user(username,password)
  #   user = User.find_by_email params[:username]
  #   if user && user.valid_password?(params[:password])
  #     user
  #   else
  #     nil
  #   end
  # end

end

app/views/oauth/account_info.html.haml
Nothing to see here, move along please

app/views/oauth/authorize.html.haml
%h1 Authorize access to your account
%p
  Would you like to authorize
  = link_to @token.client_application.name,@token.client_application.url
  (
  = link_to @token.client_application.url,@token.client_application.url
  ) to access your account?
= form_tag authorize_url do
  = hidden_field_tag "oauth_token", @token.token
  - if params[:oauth_callback]
    = hidden_field_tag "oauth_callback", params[:oauth_callback]
  %p
    = check_box_tag 'authorize'
    authorize access
  %p
    = submit_tag

app/views/oauth/authorize_failure.html.haml
%h1 You have disallowed this request

app/views/oauth/authorize_success.html.haml
%h1 You have allowed this request

app/views/oauth/oauth2_authorize.html.haml
%h1 Authorize access to your account
%p
  Would you like to authorize
  = link_to @client_application.name,@client_application.url
  (
  = link_to @client_application.url,@client_application.url
  ) to access your account?
= form_tag authorize_url do
  = hidden_field_tag "response_type", params[:response_type]
  = hidden_field_tag "client_id", params[:client_id]
  = hidden_field_tag "redirect_uri", params[:redirect_uri]
  = hidden_field_tag "state", params[:state]
  = hidden_field_tag "scope", params[:scope]
  = check_box_tag 'authorize'
  authorize access
  %p
    = submit_tag