config/routes.rb
OauthProvider::Application.routes.draw do

  resources :oauth_clients

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth',               :to => 'oauth#index',         :as => :oauth

  match '/oauth/account_info',  :to => 'oauth#account_info',  :as => :account_info

  devise_for :users

  root :to => "home#index"
end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_filter :login_required
  before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]

  alias :login_required :authenticate_user!

  def index
    @client_applications = current_user.client_applications
    @tokens = current_user.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
  end

  def new
    @client_application = ClientApplication.new
  end

  def create
    @client_application = current_user.client_applications.build(params[:client_application])
    if @client_application.save
      flash[:notice] = "Registered the information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @client_application.update_attributes(params[:client_application])
      flash[:notice] = "Updated the client information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "edit"
    end
  end

  def destroy
    @client_application.destroy
    flash[:notice] = "Destroyed the client application registration"
    redirect_to :action => "index"
  end

  private
  def get_client_application
    unless @client_application = current_user.client_applications.find(params[:id])
      flash.now[:error] = "Wrong application id"
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/views/oauth_clients/_form.html.haml
.field
  %label{:for=>"client_application_name"} Name*
  %br
  = f.text_field :name

.field
  %label{:for=>"client_application_url"} Main Application URL*
  %br
  = f.text_field :url

.field
  %label{:for=>"client_application_callback_url"} Callback URL*
  %br
  = f.text_field :callback_url

.field
  %label{:for=>"client_application_support_url"} Support URL
  %br
  = f.text_field :support_url

app/views/oauth_clients/edit.html.haml
%h1 Edit your application
= form_for :client_application do |f|
  = render :partial => "form", :locals => { :f => f }
  = submit_tag "Edit"

app/views/oauth_clients/index.html.haml
.flash= flash[:notice]
%h1 OAuth Client Applications
- unless @tokens.empty?

  %p
    The following tokens have been issued to applications in your name

  %table
    %tr
      %th Application
      %th Issued
      %th &nbsp;
    - @tokens.each do |token|
      - content_tag_for :tr, token do
        %td= link_to token.client_application.name, token.client_application.url
        %td= token.authorized_at
        %td
          - form_tag :controller => 'oauth', :action => 'revoke' do
            = hidden_field_tag 'token', token.token
            = submit_tag "Revoke!"

%h3 Application Developers

- if @client_applications.empty?
  %p
    Do you have an application you would like to register for use with us using the <a href="http://oauth.net">OAuth</a> standard?
    You must register your web application before it can make OAuth requests to this service
- else
  %p
    You have the following client applications registered:

  - @client_applications.each do |client|
    %div
      = link_to client.name, :action => :show, :id => client.id
      = link_to 'Edit', edit_oauth_client_path(client)
      = link_to 'Delete', oauth_client_path(client), :confirm => "Are you sure?", :method => :delete
%br
%h3
  = link_to "Register your application", :action => :new

app/views/oauth_clients/new.html.haml
%h1 Register a new application

= form_for :client_application, :url => { :action => :create } do |f|
  = render :partial => "form", :locals => { :f => f }
  = submit_tag "Register"

app/views/oauth_clients/show.html.haml
%h1
  OAuth details for
  =@client_application.name
%p
  %strong Consumer Key:
  %code=@client_application.key
%p
  %strong Consumer Secret:
  %code=@client_application.secret

%p
  %strong Request Token URL
  %code
    ="http#{'s' if request.ssl?}://#{request.host_with_port}#{@client_application.oauth_server.request_token_path}"

%p
  %strong Access Token URL
  %code
    ="http#{'s' if request.ssl?}://#{request.host_with_port}#{@client_application.oauth_server.access_token_path}"

%p
  %strong Authorize URL
  %code
    ="http#{'s' if request.ssl?}://#{request.host_with_port}#{@client_application.oauth_server.authorize_path}"

%p
  We support hmac-sha1 (recommended) as well as plain text in ssl mode.

= link_to 'Edit', edit_oauth_client_path(@client_application)
= link_to 'Back', oauth_clients_path